class Config:
    SECRET_KEY='YOUR_WEBSITE_SECRET_KEY'
    CREATOR='CREATOR"S CODE'
    TOKEN_KEY='TOKEN_KEY'
    SQLALCHEMY_DATABASE_URI='sqlite:///mailer.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    
    MAIL_SERVER='smtp.gmail.com'
    MAIL_PORT=587
    MAIL_USERNAME='YOUR_MAILING_EMAIL'
    MAIL_PASSWORD='APP_PASSWORD'
    MAIL_USE_TLS=True
    MAIL_USE_SSL=False
    