"""add body data to mail log

Revision ID: 5f4a6511868c
Revises: ab78233a3a07
Create Date: 2024-08-20 23:48:27.289193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4a6511868c'
down_revision = 'ab78233a3a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_data', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_log', schema=None) as batch_op:
        batch_op.drop_column('body_data')

    # ### end Alembic commands ###
