"""Templates model

Revision ID: 66110263f8d8
Revises: 0fad560695ae
Create Date: 2024-08-11 17:22:10.381477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66110263f8d8'
down_revision = '0fad560695ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sender_email', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_html', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.app_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
